# 1- Importing the necessary libraries

In [ ]:
import pandas as pd
import librosa
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

# 2- Loading the data

In [ ]:
# Loading the extracted features data
features_label = np.load('features_label.npy', allow_pickle=True)

In [ ]:
# We create an empty list where we will concatenate all the features into one long feature
features = []
for i in range(0, len(features_label)):
    features.append(np.concatenate((features_label[i][0], features_label[i][1], 
                features_label[i][2], features_label[i][3],
                features_label[i][4]), axis=0))

In [ ]:
# Similarly, we create a list where we will store all the labels
labels = []
for i in range(0, len(features_label)):
    labels.append(features_label[i][5])

In [ ]:
# Splitting the data to target and features
X = np.array(features)
y = np.array(labels)

# 3- Preprocessing

In [ ]:
# Scaling the data using StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
X.shape

(13125, 193)

In [ ]:
# Encoding the data
lb = LabelEncoder()
y = lb.fit_transform(y)

In [ ]:
y.shape

(13125,)

## Methods for predicting on new data

In [ ]:
def extract_features(files):
    # Loads the audio file as a floating point time series and assigns the default sample rate
    # Sample rate is set to 22050 by default
    X, sample_rate = librosa.load(files, res_type='kaiser_fast') 

    # Generate Mel-frequency cepstral coefficients (MFCCs) from a time series 
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)

    # Generates a Short-time Fourier transform (STFT) to use in the chroma_stft
    stft = np.abs(librosa.stft(X))

    # Computes a chromagram from a waveform or power spectrogram.
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)

    # Computes a mel-scaled spectrogram.
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)

    # Computes spectral contrast
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)

    # Computes the tonal centroid features (tonnetz)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),
    sr=sample_rate).T,axis=0)
    

    return mfccs, chroma, mel, contrast, tonnetz

def predict(filename,model):
  feat = extract_features(filename)
  features = np.concatenate((feat[0], feat[1], feat[2], feat[3],feat[4]),axis=0)
  c = scaler.transform([features])
  return model.predict(c)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print("Train set -> " , len(X_train))
print("Test set -> " , len(X_test))

Train set ->  10500
Test set ->  2625


# 4- Training

## Building SVC model

In [ ]:
from sklearn.svm import SVC

mod = SVC()

mod.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
# Accuracy
print("Accuracy Train ->", accuracy_score(y_train,mod.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod.predict(X_test)))

Accuracy Train -> 0.9961904761904762
Accuracy Test -> 0.9885714285714285
F1-score Train -> 0.9962099677847261
F1-score Test -> 0.98812351543943
Confusion Matrix Train ->
 [[5203   12]
 [  28 5257]]
Confusion Matrix Test ->
 [[1347    8]
 [  22 1248]]


##Building LogisticRegression model

In [ ]:
from sklearn.linear_model import LogisticRegression
mod_LogisticRegression = LogisticRegression(max_iter=400)

mod_LogisticRegression.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# Accuracy
print("Accuracy Train ->", accuracy_score(y_train,mod_LogisticRegression.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod_LogisticRegression.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod_LogisticRegression.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod_LogisticRegression.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod_LogisticRegression.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod_LogisticRegression.predict(X_test)))

Accuracy Train -> 0.987904761904762
Accuracy Test -> 0.984
F1-score Train -> 0.9879723458660858
F1-score Test -> 0.9835552075176195
Confusion Matrix Train ->
 [[5157   58]
 [  69 5216]]
Confusion Matrix Test ->
 [[1327   28]
 [  14 1256]]


##Building AdaBoostClassifier model

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

mod_AdaBoostClassifier = AdaBoostClassifier()

mod_AdaBoostClassifier.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [ ]:
print("Accuracy Train ->", accuracy_score(y_train,mod_AdaBoostClassifier.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod_AdaBoostClassifier.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod_AdaBoostClassifier.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod_AdaBoostClassifier.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod_AdaBoostClassifier.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod_AdaBoostClassifier.predict(X_test)))

Accuracy Train -> 0.9902857142857143
Accuracy Test -> 0.9805714285714285
F1-score Train -> 0.990339079371093
F1-score Test -> 0.9799133517132729
Confusion Matrix Train ->
 [[5170   45]
 [  57 5228]]
Confusion Matrix Test ->
 [[1330   25]
 [  26 1244]]


## Building BaggingClassifier model

In [ ]:
from sklearn.ensemble import BaggingClassifier

mod_BaggingClassifier = BaggingClassifier()

mod_BaggingClassifier.fit(X_train,y_train)

BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=10,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [ ]:
print("Accuracy Train ->", accuracy_score(y_train,mod_BaggingClassifier.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod_BaggingClassifier.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod_BaggingClassifier.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod_BaggingClassifier.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod_BaggingClassifier.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod_BaggingClassifier.predict(X_test)))

Accuracy Train -> 0.9992380952380953
Accuracy Test -> 0.9847619047619047
F1-score Train -> 0.9992427110942824
F1-score Test -> 0.9842022116903634
Confusion Matrix Train ->
 [[5214    1]
 [   7 5278]]
Confusion Matrix Test ->
 [[1339   16]
 [  24 1246]]


## Building GradientBoostingClassifier model

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

mod_GradientBoostingClassifier = GradientBoostingClassifier()

mod_GradientBoostingClassifier.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
print("Accuracy Train ->", accuracy_score(y_train,mod_GradientBoostingClassifier.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod_GradientBoostingClassifier.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod_GradientBoostingClassifier.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod_GradientBoostingClassifier.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod_GradientBoostingClassifier.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod_GradientBoostingClassifier.predict(X_test)))

Accuracy Train -> 0.9964761904761905
Accuracy Test -> 0.9870476190476191
F1-score Train -> 0.9964938879939353
F1-score Test -> 0.9865824782951854
Confusion Matrix Train ->
 [[5205   10]
 [  27 5258]]
Confusion Matrix Test ->
 [[1341   14]
 [  20 1250]]


## Building RandomForestClassifier model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

mod_RandomForestClassifier = RandomForestClassifier()

mod_RandomForestClassifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
print("Accuracy Train ->", accuracy_score(y_train,mod_RandomForestClassifier.predict(X_train)))
print("Accuracy Test ->", accuracy_score(y_test,mod_RandomForestClassifier.predict(X_test)))
# F1-score
print("F1-score Train ->", f1_score(y_train,mod_RandomForestClassifier.predict(X_train)))
print("F1-score Test ->", f1_score(y_test,mod_RandomForestClassifier.predict(X_test)))
# Confusion Matrix
print("Confusion Matrix Train ->\n", confusion_matrix(y_train,mod_RandomForestClassifier.predict(X_train)))
print("Confusion Matrix Test ->\n", confusion_matrix(y_test,mod_RandomForestClassifier.predict(X_test)))

Accuracy Train -> 1.0
Accuracy Test -> 0.9904761904761905
F1-score Train -> 1.0
F1-score Test -> 0.9901146698299723
Confusion Matrix Train ->
 [[5215    0]
 [   0 5285]]
Confusion Matrix Test ->
 [[1348    7]
 [  18 1252]]


# 5- Importing pickle and pick the perfect model

In [ ]:
import pickle

pickle.dump(mod_RandomForestClassifier, open('randomforest_model.pkl','wb'))